mybatis:
  type-aliases-package: com.flab.openmarket.domain
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.flab.openmarket.repository.typehandler
